# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Molass Library Tutorial
author: Molass Community powered by <a href="https://jupyterbook.org">Jupyter Book</a>
copyright: "2025"
logo: images/molamola.png
exclude_patterns: ["README.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_patterns: ["sec_simulation.ipynb"]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/nshimizu0721/molass-tutorial  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon : "images/molamola.png"
  use_issues_button: true
  use_repository_button: true
